on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build_docker:
    name: Build Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.2'
          extended: true
      - run: hugo --minify
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
